### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by xylophonez** [t8/weave-growth#1]
after cloning, `npm i`, then `node src/swot.js`, the output hangs on 'initializing' for a few minutes, then:

```initializing
Error: Request failed with status code 403
    at createError (/home/fn/Dev/weave-growth/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/fn/Dev/weave-growth/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/fn/Dev/weave-growth/node_modules/axios/lib/adapters/http.js:269:11)```

**Comment by xylophonez** [comment]
This went away after a few repeat attempts to run swot.js, but then #2 appeared
